# Generated by Django 5.2.1 on 2025-05-28 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='department_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='parent_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='ledger.account'),
        ),
        migrations.AddField(
            model_name='account',
            name='sub_department_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
