# Generated by Django 5.2.1 on 2025-05-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_account_department_code_account_parent_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='is_recurring_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='next_recurrence_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='recurrence_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='recurrence_pattern',
            field=models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='recurrence_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
